name: Test Project
on:
  pull_request:
     brnaches:
      -main

jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
    name: Checkout Code
    uses: actions/EndToEndMlops
name: Install Dependencies
        run: |
          python -m pip3 install --upgrade pip3
          pip3 install flake8 pytest
          if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
name: Run tests
         run: pytest
